<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Browser Opened and url lanuched]]>
    </line>
    <line>
      <![CDATA[Accepted consent popup]]>
    </line>
    <line>
      <![CDATA[Entered email address in email field]]>
    </line>
    <line>
      <![CDATA[Entered password in password field]]>
    </line>
    <line>
      <![CDATA[Clicked on Anti robot button]]>
    </line>
    <line>
      <![CDATA[Clicked on submit button]]>
    </line>
  </reporter-output>
  <suite started-at="2022-06-27T20:09:36 IST" name="Default suite" finished-at="2022-06-27T20:10:14 IST" duration-ms="38267">
    <groups>
    </groups>
    <test started-at="2022-06-27T20:09:36 IST" name="Default test" finished-at="2022-06-27T20:10:14 IST" duration-ms="38267">
      <class name="testCases.ApothekeLogin">
        <test-method is-config="true" signature="loadClass()[pri:0, instance:testCases.ApothekeLogin@229c6181]" started-at="2022-06-27T20:09:36 IST" name="loadClass" finished-at="2022-06-27T20:09:36 IST" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadClass -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testCases.ApothekeLogin@229c6181]" started-at="2022-06-27T20:09:36 IST" name="launchBrowser" finished-at="2022-06-27T20:09:39 IST" duration-ms="2883" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="loginSuccess()[pri:1, instance:testCases.ApothekeLogin@229c6181]" started-at="2022-06-27T20:09:39 IST" name="loginSuccess" finished-at="2022-06-27T20:10:14 IST" duration-ms="35025" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Verify the customer Name after login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Verify the customer Name after login expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.ApothekeLogin.loginSuccess(ApothekeLogin.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Browser Opened and url lanuched]]>
            </line>
            <line>
              <![CDATA[Accepted consent popup]]>
            </line>
            <line>
              <![CDATA[Entered email address in email field]]>
            </line>
            <line>
              <![CDATA[Entered password in password field]]>
            </line>
            <line>
              <![CDATA[Clicked on Anti robot button]]>
            </line>
            <line>
              <![CDATA[Clicked on submit button]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginSuccess -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:testCases.ApothekeLogin@229c6181]" started-at="2022-06-27T20:10:14 IST" name="closeBrowser" finished-at="2022-06-27T20:10:14 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testCases.ApothekeLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
